/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '6/1/22, 8:43 PM' 
 * Generated by 'u59841240' 
 * Generated on server 'ODAWS03-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-05%253A00&ticket=ST-63171-er5EcXNTw3OkuX7ycaTj-cas' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=PARKS.FILTEREDMONTHLYDATA 
		outdesign(addinputvars)=Work.reg_design;
	class Park / param=glm;
	model Year=Month Recreation NonRecreationVisits ConcessionerLodging 
		ConcessionerCamping TentCampers RVCampers BackcountryCampers 
		NonRecreationOvernightStays MiscOvernightStays totalvisits / showpvalues 
		selection=none;
run;

proc reg data=Work.reg_design alpha=0.05 plots(only)=(diagnostics residuals 
		observedbypredicted);
	where Park is not missing;
	ods select DiagnosticsPanel ResidualPlot ObservedByPredicted;
	model Year=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;