/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '6/1/22, 6:27 PM' 
 * Generated by 'u59841240' 
 * Generated on server 'ODAWS01-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-05%253A00&ticket=ST-62266-WsgEagffN9v4uaiRLCgP-cas' 
 *
 */

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=PARKS.FILTEREDMONTHLYDATA;
	title height=14pt "Recreation Park Count";
	vbar Park / response=Recreation datalabel;
	yaxis grid;
run;

ods graphics / reset;
title;